/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ConsentId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const StudyId = IDL.Nat;
export const HospitalId = IDL.Nat;
export const FederatedJobId = IDL.Nat;
export const RoundNumber = IDL.Nat;
export const ModelResultId = IDL.Nat;
export const RequestId = IDL.Nat;
export const JobStatus = IDL.Variant({
  'pending' : IDL.Null,
  'complete' : IDL.Null,
  'training' : IDL.Null,
});
export const FederatedJob = IDL.Record({
  'id' : FederatedJobId,
  'status' : JobStatus,
  'participatingNodes' : IDL.Vec(HospitalId),
  'studyId' : StudyId,
  'roundNumber' : RoundNumber,
  'progressPct' : IDL.Nat,
});
export const Hospital = IDL.Record({
  'id' : HospitalId,
  'name' : IDL.Text,
  'specialization' : IDL.Text,
  'adminId' : IDL.Principal,
});
export const ModelResult = IDL.Record({
  'id' : ModelResultId,
  'participatingHospitals' : IDL.Vec(HospitalId),
  'roundsCompleted' : RoundNumber,
  'studyId' : StudyId,
  'accuracy' : IDL.Nat,
});
export const PatientId = IDL.Principal;
export const PatientConsent = IDL.Record({
  'id' : ConsentId,
  'requestId' : RequestId,
  'patientId' : PatientId,
  'approved' : IDL.Bool,
});
export const RequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const ResearchRequest = IDL.Record({
  'id' : RequestId,
  'status' : RequestStatus,
  'hospitalId' : HospitalId,
  'studyId' : StudyId,
});
export const StudyStatus = IDL.Variant({
  'active' : IDL.Null,
  'complete' : IDL.Null,
  'draft' : IDL.Null,
});
export const Study = IDL.Record({
  'id' : StudyId,
  'status' : StudyStatus,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'researcherId' : IDL.Principal,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveConsent' : IDL.Func([ConsentId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createFederatedJob' : IDL.Func(
      [StudyId, IDL.Vec(HospitalId)],
      [FederatedJobId],
      [],
    ),
  'createModelResult' : IDL.Func(
      [StudyId, IDL.Nat, RoundNumber, IDL.Vec(HospitalId)],
      [ModelResultId],
      [],
    ),
  'createResearchRequest' : IDL.Func([StudyId, HospitalId], [RequestId], []),
  'createStudy' : IDL.Func([IDL.Text, IDL.Text], [StudyId], []),
  'deleteFederatedJob' : IDL.Func([FederatedJobId], [], []),
  'deleteHospital' : IDL.Func([HospitalId], [], []),
  'deleteModelResult' : IDL.Func([ModelResultId], [], []),
  'deletePatientConsent' : IDL.Func([ConsentId], [], []),
  'deleteResearchRequest' : IDL.Func([RequestId], [], []),
  'deleteStudy' : IDL.Func([StudyId], [], []),
  'getAllFederatedJobs' : IDL.Func([], [IDL.Vec(FederatedJob)], ['query']),
  'getAllHospitals' : IDL.Func([], [IDL.Vec(Hospital)], ['query']),
  'getAllModelResults' : IDL.Func([], [IDL.Vec(ModelResult)], ['query']),
  'getAllPatientConsents' : IDL.Func([], [IDL.Vec(PatientConsent)], ['query']),
  'getAllResearchRequests' : IDL.Func(
      [],
      [IDL.Vec(ResearchRequest)],
      ['query'],
    ),
  'getAllStudies' : IDL.Func([], [IDL.Vec(Study)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFederatedJob' : IDL.Func(
      [FederatedJobId],
      [IDL.Opt(FederatedJob)],
      ['query'],
    ),
  'getHospital' : IDL.Func([HospitalId], [IDL.Opt(Hospital)], ['query']),
  'getHospitalDashboard' : IDL.Func(
      [],
      [
        IDL.Record({
          'hospital' : IDL.Opt(Hospital),
          'jobs' : IDL.Vec(FederatedJob),
          'requests' : IDL.Vec(ResearchRequest),
        }),
      ],
      ['query'],
    ),
  'getModelResult' : IDL.Func(
      [ModelResultId],
      [IDL.Opt(ModelResult)],
      ['query'],
    ),
  'getPatientConsent' : IDL.Func(
      [ConsentId],
      [IDL.Opt(PatientConsent)],
      ['query'],
    ),
  'getPatientDashboard' : IDL.Func(
      [],
      [
        IDL.Record({
          'patientConsents' : IDL.Vec(PatientConsent),
          'associatedRequests' : IDL.Vec(ResearchRequest),
        }),
      ],
      ['query'],
    ),
  'getResearchRequest' : IDL.Func(
      [RequestId],
      [IDL.Opt(ResearchRequest)],
      ['query'],
    ),
  'getResearcherDashboard' : IDL.Func(
      [],
      [
        IDL.Record({
          'jobs' : IDL.Vec(FederatedJob),
          'requests' : IDL.Vec(ResearchRequest),
          'studies' : IDL.Vec(Study),
          'models' : IDL.Vec(ModelResult),
        }),
      ],
      ['query'],
    ),
  'getStudy' : IDL.Func([StudyId], [IDL.Opt(Study)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerHospital' : IDL.Func([IDL.Text, IDL.Text], [HospitalId], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitConsent' : IDL.Func([RequestId], [ConsentId], []),
  'updateFederatedJob' : IDL.Func(
      [FederatedJobId, JobStatus, RoundNumber, IDL.Nat],
      [],
      [],
    ),
  'updateHospital' : IDL.Func([HospitalId, IDL.Text, IDL.Text], [], []),
  'updateModelResult' : IDL.Func([ModelResultId, IDL.Nat, RoundNumber], [], []),
  'updateResearchRequest' : IDL.Func([RequestId, RequestStatus], [], []),
  'updateStudy' : IDL.Func([StudyId, IDL.Text, IDL.Text, StudyStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ConsentId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const StudyId = IDL.Nat;
  const HospitalId = IDL.Nat;
  const FederatedJobId = IDL.Nat;
  const RoundNumber = IDL.Nat;
  const ModelResultId = IDL.Nat;
  const RequestId = IDL.Nat;
  const JobStatus = IDL.Variant({
    'pending' : IDL.Null,
    'complete' : IDL.Null,
    'training' : IDL.Null,
  });
  const FederatedJob = IDL.Record({
    'id' : FederatedJobId,
    'status' : JobStatus,
    'participatingNodes' : IDL.Vec(HospitalId),
    'studyId' : StudyId,
    'roundNumber' : RoundNumber,
    'progressPct' : IDL.Nat,
  });
  const Hospital = IDL.Record({
    'id' : HospitalId,
    'name' : IDL.Text,
    'specialization' : IDL.Text,
    'adminId' : IDL.Principal,
  });
  const ModelResult = IDL.Record({
    'id' : ModelResultId,
    'participatingHospitals' : IDL.Vec(HospitalId),
    'roundsCompleted' : RoundNumber,
    'studyId' : StudyId,
    'accuracy' : IDL.Nat,
  });
  const PatientId = IDL.Principal;
  const PatientConsent = IDL.Record({
    'id' : ConsentId,
    'requestId' : RequestId,
    'patientId' : PatientId,
    'approved' : IDL.Bool,
  });
  const RequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const ResearchRequest = IDL.Record({
    'id' : RequestId,
    'status' : RequestStatus,
    'hospitalId' : HospitalId,
    'studyId' : StudyId,
  });
  const StudyStatus = IDL.Variant({
    'active' : IDL.Null,
    'complete' : IDL.Null,
    'draft' : IDL.Null,
  });
  const Study = IDL.Record({
    'id' : StudyId,
    'status' : StudyStatus,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'researcherId' : IDL.Principal,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveConsent' : IDL.Func([ConsentId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createFederatedJob' : IDL.Func(
        [StudyId, IDL.Vec(HospitalId)],
        [FederatedJobId],
        [],
      ),
    'createModelResult' : IDL.Func(
        [StudyId, IDL.Nat, RoundNumber, IDL.Vec(HospitalId)],
        [ModelResultId],
        [],
      ),
    'createResearchRequest' : IDL.Func([StudyId, HospitalId], [RequestId], []),
    'createStudy' : IDL.Func([IDL.Text, IDL.Text], [StudyId], []),
    'deleteFederatedJob' : IDL.Func([FederatedJobId], [], []),
    'deleteHospital' : IDL.Func([HospitalId], [], []),
    'deleteModelResult' : IDL.Func([ModelResultId], [], []),
    'deletePatientConsent' : IDL.Func([ConsentId], [], []),
    'deleteResearchRequest' : IDL.Func([RequestId], [], []),
    'deleteStudy' : IDL.Func([StudyId], [], []),
    'getAllFederatedJobs' : IDL.Func([], [IDL.Vec(FederatedJob)], ['query']),
    'getAllHospitals' : IDL.Func([], [IDL.Vec(Hospital)], ['query']),
    'getAllModelResults' : IDL.Func([], [IDL.Vec(ModelResult)], ['query']),
    'getAllPatientConsents' : IDL.Func(
        [],
        [IDL.Vec(PatientConsent)],
        ['query'],
      ),
    'getAllResearchRequests' : IDL.Func(
        [],
        [IDL.Vec(ResearchRequest)],
        ['query'],
      ),
    'getAllStudies' : IDL.Func([], [IDL.Vec(Study)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFederatedJob' : IDL.Func(
        [FederatedJobId],
        [IDL.Opt(FederatedJob)],
        ['query'],
      ),
    'getHospital' : IDL.Func([HospitalId], [IDL.Opt(Hospital)], ['query']),
    'getHospitalDashboard' : IDL.Func(
        [],
        [
          IDL.Record({
            'hospital' : IDL.Opt(Hospital),
            'jobs' : IDL.Vec(FederatedJob),
            'requests' : IDL.Vec(ResearchRequest),
          }),
        ],
        ['query'],
      ),
    'getModelResult' : IDL.Func(
        [ModelResultId],
        [IDL.Opt(ModelResult)],
        ['query'],
      ),
    'getPatientConsent' : IDL.Func(
        [ConsentId],
        [IDL.Opt(PatientConsent)],
        ['query'],
      ),
    'getPatientDashboard' : IDL.Func(
        [],
        [
          IDL.Record({
            'patientConsents' : IDL.Vec(PatientConsent),
            'associatedRequests' : IDL.Vec(ResearchRequest),
          }),
        ],
        ['query'],
      ),
    'getResearchRequest' : IDL.Func(
        [RequestId],
        [IDL.Opt(ResearchRequest)],
        ['query'],
      ),
    'getResearcherDashboard' : IDL.Func(
        [],
        [
          IDL.Record({
            'jobs' : IDL.Vec(FederatedJob),
            'requests' : IDL.Vec(ResearchRequest),
            'studies' : IDL.Vec(Study),
            'models' : IDL.Vec(ModelResult),
          }),
        ],
        ['query'],
      ),
    'getStudy' : IDL.Func([StudyId], [IDL.Opt(Study)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerHospital' : IDL.Func([IDL.Text, IDL.Text], [HospitalId], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitConsent' : IDL.Func([RequestId], [ConsentId], []),
    'updateFederatedJob' : IDL.Func(
        [FederatedJobId, JobStatus, RoundNumber, IDL.Nat],
        [],
        [],
      ),
    'updateHospital' : IDL.Func([HospitalId, IDL.Text, IDL.Text], [], []),
    'updateModelResult' : IDL.Func(
        [ModelResultId, IDL.Nat, RoundNumber],
        [],
        [],
      ),
    'updateResearchRequest' : IDL.Func([RequestId, RequestStatus], [], []),
    'updateStudy' : IDL.Func(
        [StudyId, IDL.Text, IDL.Text, StudyStatus],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };