/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ConsentId = bigint;
export interface FederatedJob {
  'id' : FederatedJobId,
  'status' : JobStatus,
  'participatingNodes' : Array<HospitalId>,
  'studyId' : StudyId,
  'roundNumber' : RoundNumber,
  'progressPct' : bigint,
}
export type FederatedJobId = bigint;
export interface Hospital {
  'id' : HospitalId,
  'name' : string,
  'specialization' : string,
  'adminId' : Principal,
}
export type HospitalId = bigint;
export type JobStatus = { 'pending' : null } |
  { 'complete' : null } |
  { 'training' : null };
export interface ModelResult {
  'id' : ModelResultId,
  'participatingHospitals' : Array<HospitalId>,
  'roundsCompleted' : RoundNumber,
  'studyId' : StudyId,
  'accuracy' : bigint,
}
export type ModelResultId = bigint;
export interface PatientConsent {
  'id' : ConsentId,
  'requestId' : RequestId,
  'patientId' : PatientId,
  'approved' : boolean,
}
export type PatientId = Principal;
export type RequestId = bigint;
export type RequestStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ResearchRequest {
  'id' : RequestId,
  'status' : RequestStatus,
  'hospitalId' : HospitalId,
  'studyId' : StudyId,
}
export type RoundNumber = bigint;
export interface Study {
  'id' : StudyId,
  'status' : StudyStatus,
  'title' : string,
  'description' : string,
  'researcherId' : Principal,
}
export type StudyId = bigint;
export type StudyStatus = { 'active' : null } |
  { 'complete' : null } |
  { 'draft' : null };
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveConsent' : ActorMethod<[ConsentId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createFederatedJob' : ActorMethod<
    [StudyId, Array<HospitalId>],
    FederatedJobId
  >,
  'createModelResult' : ActorMethod<
    [StudyId, bigint, RoundNumber, Array<HospitalId>],
    ModelResultId
  >,
  'createResearchRequest' : ActorMethod<[StudyId, HospitalId], RequestId>,
  'createStudy' : ActorMethod<[string, string], StudyId>,
  'deleteFederatedJob' : ActorMethod<[FederatedJobId], undefined>,
  'deleteHospital' : ActorMethod<[HospitalId], undefined>,
  'deleteModelResult' : ActorMethod<[ModelResultId], undefined>,
  'deletePatientConsent' : ActorMethod<[ConsentId], undefined>,
  'deleteResearchRequest' : ActorMethod<[RequestId], undefined>,
  'deleteStudy' : ActorMethod<[StudyId], undefined>,
  'getAllFederatedJobs' : ActorMethod<[], Array<FederatedJob>>,
  'getAllHospitals' : ActorMethod<[], Array<Hospital>>,
  'getAllModelResults' : ActorMethod<[], Array<ModelResult>>,
  'getAllPatientConsents' : ActorMethod<[], Array<PatientConsent>>,
  'getAllResearchRequests' : ActorMethod<[], Array<ResearchRequest>>,
  'getAllStudies' : ActorMethod<[], Array<Study>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFederatedJob' : ActorMethod<[FederatedJobId], [] | [FederatedJob]>,
  'getHospital' : ActorMethod<[HospitalId], [] | [Hospital]>,
  'getHospitalDashboard' : ActorMethod<
    [],
    {
      'hospital' : [] | [Hospital],
      'jobs' : Array<FederatedJob>,
      'requests' : Array<ResearchRequest>,
    }
  >,
  'getModelResult' : ActorMethod<[ModelResultId], [] | [ModelResult]>,
  'getPatientConsent' : ActorMethod<[ConsentId], [] | [PatientConsent]>,
  'getPatientDashboard' : ActorMethod<
    [],
    {
      'patientConsents' : Array<PatientConsent>,
      'associatedRequests' : Array<ResearchRequest>,
    }
  >,
  'getResearchRequest' : ActorMethod<[RequestId], [] | [ResearchRequest]>,
  'getResearcherDashboard' : ActorMethod<
    [],
    {
      'jobs' : Array<FederatedJob>,
      'requests' : Array<ResearchRequest>,
      'studies' : Array<Study>,
      'models' : Array<ModelResult>,
    }
  >,
  'getStudy' : ActorMethod<[StudyId], [] | [Study]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerHospital' : ActorMethod<[string, string], HospitalId>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitConsent' : ActorMethod<[RequestId], ConsentId>,
  'updateFederatedJob' : ActorMethod<
    [FederatedJobId, JobStatus, RoundNumber, bigint],
    undefined
  >,
  'updateHospital' : ActorMethod<[HospitalId, string, string], undefined>,
  'updateModelResult' : ActorMethod<
    [ModelResultId, bigint, RoundNumber],
    undefined
  >,
  'updateResearchRequest' : ActorMethod<[RequestId, RequestStatus], undefined>,
  'updateStudy' : ActorMethod<
    [StudyId, string, string, StudyStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];