/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ResearchRequest {
    id: RequestId;
    status: RequestStatus;
    hospitalId: HospitalId;
    studyId: StudyId;
}
export type RoundNumber = bigint;
export type HospitalId = bigint;
export type StudyId = bigint;
export interface ModelResult {
    id: ModelResultId;
    participatingHospitals: Array<HospitalId>;
    roundsCompleted: RoundNumber;
    studyId: StudyId;
    accuracy: bigint;
}
export type PatientId = Principal;
export type ConsentId = bigint;
export type ModelResultId = bigint;
export interface FederatedJob {
    id: FederatedJobId;
    status: JobStatus;
    participatingNodes: Array<HospitalId>;
    studyId: StudyId;
    roundNumber: RoundNumber;
    progressPct: bigint;
}
export type FederatedJobId = bigint;
export interface PatientConsent {
    id: ConsentId;
    requestId: RequestId;
    patientId: PatientId;
    approved: boolean;
}
export interface Hospital {
    id: HospitalId;
    name: string;
    specialization: string;
    adminId: Principal;
}
export interface Study {
    id: StudyId;
    status: StudyStatus;
    title: string;
    description: string;
    researcherId: Principal;
}
export type RequestId = bigint;
export interface UserProfile {
    name: string;
    role: string;
}
export enum JobStatus {
    pending = "pending",
    complete = "complete",
    training = "training"
}
export enum RequestStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum StudyStatus {
    active = "active",
    complete = "complete",
    draft = "draft"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    approveConsent(consentId: ConsentId): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createFederatedJob(studyId: StudyId, participatingNodes: Array<HospitalId>): Promise<FederatedJobId>;
    createModelResult(studyId: StudyId, accuracy: bigint, roundsCompleted: RoundNumber, participatingHospitals: Array<HospitalId>): Promise<ModelResultId>;
    createResearchRequest(studyId: StudyId, hospitalId: HospitalId): Promise<RequestId>;
    createStudy(title: string, description: string): Promise<StudyId>;
    deleteFederatedJob(jobId: FederatedJobId): Promise<void>;
    deleteHospital(hospitalId: HospitalId): Promise<void>;
    deleteModelResult(resultId: ModelResultId): Promise<void>;
    deletePatientConsent(consentId: ConsentId): Promise<void>;
    deleteResearchRequest(requestId: RequestId): Promise<void>;
    deleteStudy(studyId: StudyId): Promise<void>;
    getAllFederatedJobs(): Promise<Array<FederatedJob>>;
    getAllHospitals(): Promise<Array<Hospital>>;
    getAllModelResults(): Promise<Array<ModelResult>>;
    getAllPatientConsents(): Promise<Array<PatientConsent>>;
    getAllResearchRequests(): Promise<Array<ResearchRequest>>;
    getAllStudies(): Promise<Array<Study>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFederatedJob(jobId: FederatedJobId): Promise<FederatedJob | null>;
    getHospital(hospitalId: HospitalId): Promise<Hospital | null>;
    getHospitalDashboard(): Promise<{
        hospital?: Hospital;
        jobs: Array<FederatedJob>;
        requests: Array<ResearchRequest>;
    }>;
    getModelResult(resultId: ModelResultId): Promise<ModelResult | null>;
    getPatientConsent(consentId: ConsentId): Promise<PatientConsent | null>;
    getPatientDashboard(): Promise<{
        patientConsents: Array<PatientConsent>;
        associatedRequests: Array<ResearchRequest>;
    }>;
    getResearchRequest(requestId: RequestId): Promise<ResearchRequest | null>;
    getResearcherDashboard(): Promise<{
        jobs: Array<FederatedJob>;
        requests: Array<ResearchRequest>;
        studies: Array<Study>;
        models: Array<ModelResult>;
    }>;
    getStudy(studyId: StudyId): Promise<Study | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    registerHospital(name: string, specialization: string): Promise<HospitalId>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitConsent(requestId: RequestId): Promise<ConsentId>;
    updateFederatedJob(jobId: FederatedJobId, status: JobStatus, roundNumber: RoundNumber, progressPct: bigint): Promise<void>;
    updateHospital(hospitalId: HospitalId, name: string, specialization: string): Promise<void>;
    updateModelResult(resultId: ModelResultId, accuracy: bigint, roundsCompleted: RoundNumber): Promise<void>;
    updateResearchRequest(requestId: RequestId, status: RequestStatus): Promise<void>;
    updateStudy(studyId: StudyId, title: string, description: string, status: StudyStatus): Promise<void>;
}
import type { FederatedJob as _FederatedJob, FederatedJobId as _FederatedJobId, Hospital as _Hospital, HospitalId as _HospitalId, JobStatus as _JobStatus, ModelResult as _ModelResult, PatientConsent as _PatientConsent, RequestId as _RequestId, RequestStatus as _RequestStatus, ResearchRequest as _ResearchRequest, RoundNumber as _RoundNumber, Study as _Study, StudyId as _StudyId, StudyStatus as _StudyStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async approveConsent(arg0: ConsentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveConsent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveConsent(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createFederatedJob(arg0: StudyId, arg1: Array<HospitalId>): Promise<FederatedJobId> {
        if (this.processError) {
            try {
                const result = await this.actor.createFederatedJob(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFederatedJob(arg0, arg1);
            return result;
        }
    }
    async createModelResult(arg0: StudyId, arg1: bigint, arg2: RoundNumber, arg3: Array<HospitalId>): Promise<ModelResultId> {
        if (this.processError) {
            try {
                const result = await this.actor.createModelResult(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createModelResult(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createResearchRequest(arg0: StudyId, arg1: HospitalId): Promise<RequestId> {
        if (this.processError) {
            try {
                const result = await this.actor.createResearchRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createResearchRequest(arg0, arg1);
            return result;
        }
    }
    async createStudy(arg0: string, arg1: string): Promise<StudyId> {
        if (this.processError) {
            try {
                const result = await this.actor.createStudy(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStudy(arg0, arg1);
            return result;
        }
    }
    async deleteFederatedJob(arg0: FederatedJobId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFederatedJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFederatedJob(arg0);
            return result;
        }
    }
    async deleteHospital(arg0: HospitalId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHospital(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHospital(arg0);
            return result;
        }
    }
    async deleteModelResult(arg0: ModelResultId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteModelResult(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteModelResult(arg0);
            return result;
        }
    }
    async deletePatientConsent(arg0: ConsentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePatientConsent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePatientConsent(arg0);
            return result;
        }
    }
    async deleteResearchRequest(arg0: RequestId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteResearchRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteResearchRequest(arg0);
            return result;
        }
    }
    async deleteStudy(arg0: StudyId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudy(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudy(arg0);
            return result;
        }
    }
    async getAllFederatedJobs(): Promise<Array<FederatedJob>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFederatedJobs();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFederatedJobs();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllHospitals(): Promise<Array<Hospital>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHospitals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHospitals();
            return result;
        }
    }
    async getAllModelResults(): Promise<Array<ModelResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllModelResults();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllModelResults();
            return result;
        }
    }
    async getAllPatientConsents(): Promise<Array<PatientConsent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPatientConsents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPatientConsents();
            return result;
        }
    }
    async getAllResearchRequests(): Promise<Array<ResearchRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllResearchRequests();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllResearchRequests();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStudies(): Promise<Array<Study>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudies();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudies();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFederatedJob(arg0: FederatedJobId): Promise<FederatedJob | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFederatedJob(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFederatedJob(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHospital(arg0: HospitalId): Promise<Hospital | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHospital(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHospital(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHospitalDashboard(): Promise<{
        hospital?: Hospital;
        jobs: Array<FederatedJob>;
        requests: Array<ResearchRequest>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getHospitalDashboard();
                return from_candid_record_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHospitalDashboard();
            return from_candid_record_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getModelResult(arg0: ModelResultId): Promise<ModelResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getModelResult(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getModelResult(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPatientConsent(arg0: ConsentId): Promise<PatientConsent | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatientConsent(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatientConsent(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPatientDashboard(): Promise<{
        patientConsents: Array<PatientConsent>;
        associatedRequests: Array<ResearchRequest>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatientDashboard();
                return from_candid_record_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatientDashboard();
            return from_candid_record_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResearchRequest(arg0: RequestId): Promise<ResearchRequest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getResearchRequest(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResearchRequest(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResearcherDashboard(): Promise<{
        jobs: Array<FederatedJob>;
        requests: Array<ResearchRequest>;
        studies: Array<Study>;
        models: Array<ModelResult>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getResearcherDashboard();
                return from_candid_record_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResearcherDashboard();
            return from_candid_record_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudy(arg0: StudyId): Promise<Study | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudy(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudy(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerHospital(arg0: string, arg1: string): Promise<HospitalId> {
        if (this.processError) {
            try {
                const result = await this.actor.registerHospital(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerHospital(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitConsent(arg0: RequestId): Promise<ConsentId> {
        if (this.processError) {
            try {
                const result = await this.actor.submitConsent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitConsent(arg0);
            return result;
        }
    }
    async updateFederatedJob(arg0: FederatedJobId, arg1: JobStatus, arg2: RoundNumber, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFederatedJob(arg0, to_candid_JobStatus_n30(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFederatedJob(arg0, to_candid_JobStatus_n30(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async updateHospital(arg0: HospitalId, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHospital(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHospital(arg0, arg1, arg2);
            return result;
        }
    }
    async updateModelResult(arg0: ModelResultId, arg1: bigint, arg2: RoundNumber): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateModelResult(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateModelResult(arg0, arg1, arg2);
            return result;
        }
    }
    async updateResearchRequest(arg0: RequestId, arg1: RequestStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateResearchRequest(arg0, to_candid_RequestStatus_n32(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateResearchRequest(arg0, to_candid_RequestStatus_n32(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateStudy(arg0: StudyId, arg1: string, arg2: string, arg3: StudyStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudy(arg0, arg1, arg2, to_candid_StudyStatus_n34(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudy(arg0, arg1, arg2, to_candid_StudyStatus_n34(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
}
function from_candid_FederatedJob_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FederatedJob): FederatedJob {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_JobStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobStatus): JobStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_RequestStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RequestStatus): RequestStatus {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_ResearchRequest_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResearchRequest): ResearchRequest {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_StudyStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudyStatus): StudyStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Study_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Study): Study {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FederatedJob]): FederatedJob | null {
    return value.length === 0 ? null : from_candid_FederatedJob_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Hospital]): Hospital | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ModelResult]): ModelResult | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PatientConsent]): PatientConsent | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ResearchRequest]): ResearchRequest | null {
    return value.length === 0 ? null : from_candid_ResearchRequest_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Study]): Study | null {
    return value.length === 0 ? null : from_candid_Study_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RequestId;
    status: _RequestStatus;
    hospitalId: _HospitalId;
    studyId: _StudyId;
}): {
    id: RequestId;
    status: RequestStatus;
    hospitalId: HospitalId;
    studyId: StudyId;
} {
    return {
        id: value.id,
        status: from_candid_RequestStatus_n11(_uploadFile, _downloadFile, value.status),
        hospitalId: value.hospitalId,
        studyId: value.studyId
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _StudyId;
    status: _StudyStatus;
    title: string;
    description: string;
    researcherId: Principal;
}): {
    id: StudyId;
    status: StudyStatus;
    title: string;
    description: string;
    researcherId: Principal;
} {
    return {
        id: value.id,
        status: from_candid_StudyStatus_n16(_uploadFile, _downloadFile, value.status),
        title: value.title,
        description: value.description,
        researcherId: value.researcherId
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hospital: [] | [_Hospital];
    jobs: Array<_FederatedJob>;
    requests: Array<_ResearchRequest>;
}): {
    hospital?: Hospital;
    jobs: Array<FederatedJob>;
    requests: Array<ResearchRequest>;
} {
    return {
        hospital: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.hospital)),
        jobs: from_candid_vec_n3(_uploadFile, _downloadFile, value.jobs),
        requests: from_candid_vec_n8(_uploadFile, _downloadFile, value.requests)
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    patientConsents: Array<_PatientConsent>;
    associatedRequests: Array<_ResearchRequest>;
}): {
    patientConsents: Array<PatientConsent>;
    associatedRequests: Array<ResearchRequest>;
} {
    return {
        patientConsents: value.patientConsents,
        associatedRequests: from_candid_vec_n8(_uploadFile, _downloadFile, value.associatedRequests)
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    jobs: Array<_FederatedJob>;
    requests: Array<_ResearchRequest>;
    studies: Array<_Study>;
    models: Array<_ModelResult>;
}): {
    jobs: Array<FederatedJob>;
    requests: Array<ResearchRequest>;
    studies: Array<Study>;
    models: Array<ModelResult>;
} {
    return {
        jobs: from_candid_vec_n3(_uploadFile, _downloadFile, value.jobs),
        requests: from_candid_vec_n8(_uploadFile, _downloadFile, value.requests),
        studies: from_candid_vec_n13(_uploadFile, _downloadFile, value.studies),
        models: value.models
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _FederatedJobId;
    status: _JobStatus;
    participatingNodes: Array<_HospitalId>;
    studyId: _StudyId;
    roundNumber: _RoundNumber;
    progressPct: bigint;
}): {
    id: FederatedJobId;
    status: JobStatus;
    participatingNodes: Array<HospitalId>;
    studyId: StudyId;
    roundNumber: RoundNumber;
    progressPct: bigint;
} {
    return {
        id: value.id,
        status: from_candid_JobStatus_n6(_uploadFile, _downloadFile, value.status),
        participatingNodes: value.participatingNodes,
        studyId: value.studyId,
        roundNumber: value.roundNumber,
        progressPct: value.progressPct
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): RequestStatus {
    return "pending" in value ? RequestStatus.pending : "approved" in value ? RequestStatus.approved : "rejected" in value ? RequestStatus.rejected : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    complete: null;
} | {
    draft: null;
}): StudyStatus {
    return "active" in value ? StudyStatus.active : "complete" in value ? StudyStatus.complete : "draft" in value ? StudyStatus.draft : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    complete: null;
} | {
    training: null;
}): JobStatus {
    return "pending" in value ? JobStatus.pending : "complete" in value ? JobStatus.complete : "training" in value ? JobStatus.training : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Study>): Array<Study> {
    return value.map((x)=>from_candid_Study_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FederatedJob>): Array<FederatedJob> {
    return value.map((x)=>from_candid_FederatedJob_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ResearchRequest>): Array<ResearchRequest> {
    return value.map((x)=>from_candid_ResearchRequest_n9(_uploadFile, _downloadFile, x));
}
function to_candid_JobStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobStatus): _JobStatus {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_RequestStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RequestStatus): _RequestStatus {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid_StudyStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudyStatus): _StudyStatus {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobStatus): {
    pending: null;
} | {
    complete: null;
} | {
    training: null;
} {
    return value == JobStatus.pending ? {
        pending: null
    } : value == JobStatus.complete ? {
        complete: null
    } : value == JobStatus.training ? {
        training: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RequestStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == RequestStatus.pending ? {
        pending: null
    } : value == RequestStatus.approved ? {
        approved: null
    } : value == RequestStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StudyStatus): {
    active: null;
} | {
    complete: null;
} | {
    draft: null;
} {
    return value == StudyStatus.active ? {
        active: null
    } : value == StudyStatus.complete ? {
        complete: null
    } : value == StudyStatus.draft ? {
        draft: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
